version: 2

sources:
  - name: northwind
    database: RAW
    schema: NORTHWIND

    tables:
      - name: Customers
        columns:
          - name: CustomerId
            tests:
              - unique

      - name: Products
        columns:
          - name: ProductId
            tests:
              - unique

      - name: Suppliers
        columns:
          - name: SupplierId
            tests:
              - unique

      - name: Categories
        columns:
          - name: CategoryId
            tests:
              - unique

      - name: Employees
        columns:
          - name: EmployeeId
            tests:
              - unique

      - name: Shippers
        columns:
          - name: ShipperID
            tests:
              - unique

      - name: Orders
        columns:
          - name: OrderId
            tests:
              - unique

      - name: Order_Details
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - OrderId
                - ProductId